name: tests

on:
  push:
    branches:
      - '4.x'
      - '5.x'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        include:
          - php: 8.2
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding standards
        run: composer cs:check

      - name: Code sniffer
        run: composer sniffer:check

      - name: Static analysis
        run: composer stan

      - name: Tests
        if: ${{ !matrix.analysis }}
        run: composer test

      - name: Tests with coverage
        if: matrix.analysis
        run: composer test:coverage

      - name: Upload coverage results to Coveralls
        if: matrix.analysis
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/coverage/clover.xml -v
